package Vista;

import Controlador.ControlPermisos;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class frmPermiso extends javax.swing.JFrame {

    ControlPermisos ctPermisos = new ControlPermisos();

    public frmPermiso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuarioRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btRegistrarte = new java.awt.Button();
        button1 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        c2 = new java.awt.Checkbox();
        c3 = new java.awt.Checkbox();
        c4 = new java.awt.Checkbox();
        c5 = new java.awt.Checkbox();
        c6 = new java.awt.Checkbox();
        c7 = new java.awt.Checkbox();
        c8 = new java.awt.Checkbox();
        c9 = new java.awt.Checkbox();
        c10 = new java.awt.Checkbox();
        c11 = new java.awt.Checkbox();
        c1 = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de usuarios y permisos.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 40));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 470, 10));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registrarte");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtContraseña.setForeground(new java.awt.Color(51, 51, 55));
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContraseña.setCaretColor(new java.awt.Color(51, 51, 55));
        txtContraseña.setSelectedTextColor(new java.awt.Color(51, 51, 55));
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 30));

        txtUsuarioRegistro.setForeground(new java.awt.Color(51, 51, 55));
        txtUsuarioRegistro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuarioRegistro.setCaretColor(new java.awt.Color(51, 51, 55));
        txtUsuarioRegistro.setSelectedTextColor(new java.awt.Color(51, 51, 55));
        txtUsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioRegistroKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btRegistrarte.setActionCommand("btResgidtro");
        btRegistrarte.setBackground(new java.awt.Color(0, 255, 0));
        btRegistrarte.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btRegistrarte.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrarte.setLabel("Registrarte");
        btRegistrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarteActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 150, 40));

        button1.setBackground(new java.awt.Color(29, 91, 121));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Menú");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\"Gestión de Permisos\"", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cambria", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);

        c2.setBackground(new java.awt.Color(204, 204, 255));
        c2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setLabel("Clientes.");

        c3.setBackground(new java.awt.Color(204, 204, 255));
        c3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c3.setForeground(new java.awt.Color(0, 0, 0));
        c3.setLabel("Proveedor.");

        c4.setBackground(new java.awt.Color(204, 204, 255));
        c4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c4.setForeground(new java.awt.Color(0, 0, 0));
        c4.setLabel("Factura.");

        c5.setBackground(new java.awt.Color(204, 204, 255));
        c5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c5.setForeground(new java.awt.Color(0, 0, 0));
        c5.setLabel("Compra.");

        c6.setBackground(new java.awt.Color(204, 204, 255));
        c6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c6.setForeground(new java.awt.Color(0, 0, 0));
        c6.setLabel("Kardex.");

        c7.setBackground(new java.awt.Color(204, 204, 255));
        c7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c7.setForeground(new java.awt.Color(0, 0, 0));
        c7.setLabel("Provincia.");

        c8.setBackground(new java.awt.Color(204, 204, 255));
        c8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c8.setForeground(new java.awt.Color(0, 0, 0));
        c8.setLabel("Ciudad.");

        c9.setBackground(new java.awt.Color(204, 204, 255));
        c9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c9.setForeground(new java.awt.Color(0, 0, 0));
        c9.setLabel("Listado de ventas.");

        c10.setBackground(new java.awt.Color(204, 204, 255));
        c10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c10.setForeground(new java.awt.Color(0, 0, 0));
        c10.setLabel("Listado de compras.");

        c11.setBackground(new java.awt.Color(204, 204, 255));
        c11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c11.setForeground(new java.awt.Color(0, 0, 0));
        c11.setLabel("Gestión de usuarios y permisos.");

        c1.setBackground(new java.awt.Color(204, 204, 255));
        c1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setLabel("Productos.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 450, 220));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Es rápido y fácil .");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        this.dispose();
        frmInicio fmrin = new frmInicio();
        fmrin.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void btRegistrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarteActionPerformed
        boolean aux;
        aux = ctPermisos.IngresarNuevosUsers(txtUsuarioRegistro.getText(), txtContraseña.getText(), c1.getState(), c2.getState(), c3.getState(), c4.getState(), c5.getState(), c6.getState(), c7.getState(), c8.getState(), c9.getState(), c10.getState(), c11.getState());
        if (aux == true) {
            JOptionPane.showMessageDialog(null, "Usuario fue registrado correctamente.");
            txtUsuarioRegistro.setText("");
            txtContraseña.setText("");
            c1.setState(false);
            c2.setState(false);
            c3.setState(false);
            c4.setState(false);
            c5.setState(false);
            c6.setState(false);
            c7.setState(false);
            c8.setState(false);
            c9.setState(false);
            c10.setState(false);
            c11.setState(false);
        } else {
            txtUsuarioRegistro.setText("");
            txtContraseña.setText("");
            c1.setState(false);
            c2.setState(false);
            c3.setState(false);
            c4.setState(false);
            c5.setState(false);
            c6.setState(false);
            c7.setState(false);
            c8.setState(false);
            c9.setState(false);
            c10.setState(false);
            c11.setState(false);
        }

    }//GEN-LAST:event_btRegistrarteActionPerformed

    private void txtUsuarioRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioRegistroKeyTyped
       char c = evt.getKeyChar();
        String text = this.txtUsuarioRegistro.getText().trim();

        if (!Character.isLetterOrDigit(c) || text.length() >= 15) {
            evt.consume(); // Evita ingresar caracteres no permitidos o exceder la longitud máxima
        }
    }//GEN-LAST:event_txtUsuarioRegistroKeyTyped

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
   char c = evt.getKeyChar();
        String text = this.txtContraseña.getText().trim();

        if (!Character.isLetterOrDigit(c) || text.length() >= 15) {
            evt.consume(); // Evita ingresar caracteres no permitidos o exceder la longitud máxima
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPermiso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btRegistrarte;
    private java.awt.Button button1;
    private java.awt.Checkbox c1;
    private java.awt.Checkbox c10;
    private java.awt.Checkbox c11;
    private java.awt.Checkbox c2;
    private java.awt.Checkbox c3;
    private java.awt.Checkbox c4;
    private java.awt.Checkbox c5;
    private java.awt.Checkbox c6;
    private java.awt.Checkbox c7;
    private java.awt.Checkbox c8;
    private java.awt.Checkbox c9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
